version: '3.9' # optional since v1.27.0
services:
  ########## postgres
  postgresdev:
    env_file: ./.env
    image: postgres:latest@sha256:7f29c02ba9eeff4de9a9f414d803faa0e6fe5e8d15ebe217e3e418c82e652b35
    # restart: unless-stopped
    # user: postgres
    # network_mode: host
    ports:
      - ${DB_HOST}:${DB_PORT}:5432
      # - 5432:5432
    container_name: postgresdev
    volumes:
      #     - ~/data/postgres:/var/lib/postgresql/data
      - /tmp/db/psql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest@sha256:61fd25f428c155027fb2aa74b913d317af11a14f55e6135484b5e86a8840520b
    # restart: unless-stopped
    # network_mode: host
    depends_on:
      - postgresdev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      # PGADMIN_LISTEN_PORT: 9001
    ports:
      - 127.0.0.1:9001:80
      # - 9001:80
