# https://github.com/clemenscodes/nx-plugins/blob/main/codecov.yml
#
codecov:
  notify:
    require_ci_to_pass: yes
comment:
  layout: 'header, diff, flags, components'
coverage:
  precision: 2
  round: down
  status:
    project: yes
component_management:
  default_rules:
    statuses:
      - type: patch
        target: auto
  individual_components:
    - component_id: example-express-app
      paths:
        - 'coverage/apps/example-express-app/**'
    - component_id: example-angular-app
      paths:
        - 'coverage/apps/example-angular-app/**'
    - component_id: example-node-lib
      paths:
        - 'coverage/libs/example-node-lib/**'
