name: Setup CI
runs:
  using: composite
  steps:
    # get git lfs objects
    - name: Checkout LFS objects
      shell: bash
      run: git lfs checkout
    - name: Pull LFS objects
      shell: bash
      run: git lfs pull
    # setup go
    - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
      name: Setup Go
      with: # Set the Go version to use
        go-version: 1.22.2
    # setup dotnet
    - uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4
      name: Setup .NET
    # setup python
    - uses: actions/setup-python@v5
      name: Setup Python
      with:
        python-version: 3.12
    # setup node.js
    - name: Setup Node.js 22
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        node-version: 22.1.0
    # setup pnpm
    - uses: pnpm/action-setup@v3
      name: Install pnpm
      # respects package.json packageManager if present when no version is specified
      with:
        run_install: false
    # enabling corepack prevents the need to install it
    # and makes sure it respects package.json packageManager
    # - name: enable corepack
    #   shell: bash
    #   run: corepack enable
    # get cache
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    # install nx cli
    - name: Install Nx CLI
      shell: bash
      run: npm install -g nx@latest
    # install dependencies
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
  # - name: Init tasks
  #   run: nx run-many -t init
