---
POST http://localhost:3000/auth/login
Content-Type: application/json

# must add password
{
  "email": "test@gipo.dev",
  "password": "12345678"
}

---
POST http://localhost:3000/auth/signup
Content-Type: application/json

# must add password, passwordConfirm
{
  "email": "test@gipo.dev",
  "password": "12345678",
  "passwordConfirm": "12345678"
}

---
GET http://localhost:3000/auth/refresh

---
POST http://localhost:3000/auth/logout
Content-Type: application/json

{
  "title": "Learn Node.js",
  "dueDate": "2020-12-31"
}
