# TODO: must implement
---
# wrong url
GET http://localhost:3000/apiaa

---
# fetch all todos (no completed)
GET http://localhost:3000/api/todos

---
# fetch all todos (include completed)
GET http://localhost:3000/api/todos?showCompleted=true

---
# fetch single todo
GET http://localhost:3000/api/todos/:id

---
# create a todo
POST http://localhost:3000/api/todos
Content-Type: application/json

{
  "title": "Learn Node.js",
  "dueDate": "2020-12-31"
}

---
# update a todo
PATCH http://localhost:3000/api/todos/:id
Content-Type: application/json

{
  "title": "Learn Node.js",
  "dueDate": "2020-12-31",
  "completed": true
}

---
# delete a todo
POST http://localhost:3000/api/todos/:id
