# TODO: must implement
---
# fetch me page
GET http://localhost:3000/api/users/me

---
# fetch all users (no completed)
GET http://localhost:3000/api/users

---
# fetch all users (include completed)
GET http://localhost:3000/api/users?showCompleted=true

---
# fetch single user
GET http://localhost:3000/api/users/:id

---
# create a user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "title": "Learn Node.js",
  "dueDate": "2020-12-31"
}

---
# update a user
POST http://localhost:3000/api/users/:id
Content-Type: application/json

{
  "title": "Learn Node.js",
  "dueDate": "2020-12-31",
  "completed": true
}

---
# delete a user
POST http://localhost:3000/api/users/:id
