version: '3.9'
services:
  loki:
    image: grafana/loki:3.0.0
    # profiles: [full]
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
  promtail:
    # profiles: [full]
    image: grafana/promtail:3.0.0
    volumes:
      - /tmp/loki/promtail/var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
  grafana:
    # profiles: [full]
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - '127.0.0.1:3200:3000'
