# https://nx.dev/ci/recipes/set-up/monorepo-ci-github-actions
# https://medium.com/ngconf/running-nx-affected-commands-in-github-actions-e126b808506c
# we want to release the packages that have been affected by the changes
# compare head to head-1

# IMP: added as last step to lint test build dev
name: pre-release
on:
  workflow_run:
    workflows: ['Lint Test Build Dev']
    types:
      - completed
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-22.04
    permissions: 'write-all'
    # contents: 'read'
    # actions: 'write'
    steps:
      - name: Setup Git
        # required to commit the changes
        run: |
          git config --global user.name "gipo355"
          git config --global user.email "91525512+gipo355@users.noreply.github.com"
      # ...
      # checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # fetch all history so that nx affected can compare with older commits
          fetch-depth: 0
      # setup node
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.5.0
      # setup pnpm
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8.14.0
          run_install: false
      # get cache
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      # install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      # sets the base and head SHAs required for the nx affected commands in CI
      - name:
          Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'dev'
      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
      # Bump semver packages
      - name: release affected packages
        run: |
          pnpx nx affected -t version --noVerify
          git push --no-verify
