name: 'Lint Test Build Dev'
on:
  push:
    branches:
      - dev
  # should separate this
  # pull_request:
  #   branches:
  #     - dev
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  deploy:
    name: Lint and Test
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # fetch all history so that nx affected can compare with older commits
          fetch-depth: 0
      # setup node
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.5.0
      - name: setup go
        uses: actions/setup-go@v5
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      # setup pnpm
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8.14.0
          run_install: false
      # get cache
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      # install dependencies
      - name: Install NX Cli
        run: pnpm add -g nx
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      # testing nx affected
      - name:
          Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        with:
          # must compare to dev branch
          main-branch-name: 'dev'
      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
        # This line is needed for nx affected to work when CI is running on a PR
        # - name: Set up main branch for affected commands in PR
        #   run: git branch --track dev origin/dev
        # if: ${{ github.event_name == 'pull_request' }}
      - name: lint test build
        run: nx affected -t lint test build
    # Bump semver packages
    # FIXME: broken, always the same release, why?
    # - name: Setup Git
    #   # required to commit the changes
    #   run: |
    #     git config --global user.name "gipo355"
    #     git config --global user.email "91525512+gipo355@users.noreply.github.com"
    #   # TODO: is this the best (logically) place to put this? on every push to dev
    #   # we update the version of the affected packages
    # - name: release affected packages
    #   run: |
    #     pnpx nx affected -t version --noVerify
    #     git push --no-verify
