name: Lint Test Build Workflow
on:
  # push:
  #   branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch: {}
jobs:
  LintTestBuild:
    permissions:
      # Needed for nx-set-shas when run on the main branch
      actions: read
      contents: read
    name: Lint and Test Job
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      # checkout
      - name: Checkout Repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          fetch-depth: 0
          lfs: true
          # persist-credentials: false
      - uses: ./.github/actions/ci-setup
        name: Setup CI environment
      # testing nx affected
      - name:
          Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        with:
          # must compare to branch
          main-branch-name: 'main'
      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
      - name: Set up main branch for affected commands in PR
        run: git branch --track dev origin/main
        if: ${{ github.event_name == 'pull_request' }}
      - name: lint test build
        run: nx affected -t lint test build
