name: 'Dependency Review Workflow'
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  dependency-review:
    name: Dependency Review Job
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@0c155c5e8556a497adf53f2c18edabf945ed8e70 # v4
