name: 'Dependency Review Workflow'
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  dependency-review:
    name: Dependency Review Job
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@72eb03d02c7872a771aacd928f3123ac62ad6d3a # v4
